[package]
name = "utrackr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["net", "macros"] }
openssl = "0.10.38"
crc64fast = "1.0"
redis = { version = "0.21", features = ["tokio-comp"] }
# futures = "0.3"

[features]
simd = ["crc64fast/pmull"]
