[package]
name = "utrackr-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "time", "net", "macros"] }
openssl = "0.10.38"
blake3 = "1.2.0"
log = { version = "0.4", features = ["release_max_level_warn"] }
redis = { version = "0.21.4", features = ["aio", "tokio-comp"] }
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }
bb8-redis = "0.10.1"
