[package]
name = "utrackr-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "time", "net", "macros"] }
blake3 = "1.2.0"
log = { version = "0.4", features = ["release_max_level_warn"] }
serde = { version = "1", features = ["derive"] }
mongodb = "2.1.0"
futures = "0.3"
